const CONST = {
    GRAPHQL_BASE_URL: process.env.REACT_APP_GRAPHQL_BASE_URL,
    GRAPHQL_WSLINK: process.env.REACT_APP_GRAPHQL_WSLINK,
    HASURA_CLIENT_SECRET: process.env.REACT_APP_HASURA_CLIENT_SECRET,
}

export default CONST;